vec4 outColor = vec4(1.0);
vec3 outNormal = normalize(vNormal);
vec3 outNormalMap = vec3( 0.0 );
float outSSN = 0.0;
float outEmissionIntensity = 0.0;
float outRoughness = 0.5;
float outMetalic = 0.0;
vec3 outPos = vPos;
float outEnv = 1.0;