name: deploy-pages

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Install shader-minifier
        run: npm install shader-minifier
      - name: Setup shader-minifier PATH
        run: echo "$(pwd)/node_modules/shader-minifier/binary" >> $GITHUB_PATH
      - name: Build demo
        run: npm run prebuild
      - name: Prepare Pages artifact
        run: |
          mkdir -p public
          cp -r dist/* public/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
        with:
          preview: ${{ github.event_name == 'pull_request' }}

