name: tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  vitest:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

